// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace FootballPredictorML.Model
{
    public class ModelInput
    {
        [ColumnName("Id"), LoadColumn(0)]
        public float Id { get; set; }


        [ColumnName("MatchId"), LoadColumn(1)]
        public float MatchId { get; set; }


        [ColumnName("SeasonId"), LoadColumn(2)]
        public float SeasonId { get; set; }


        [ColumnName("Matchday"), LoadColumn(3)]
        public float Matchday { get; set; }


        [ColumnName("HomeTeam"), LoadColumn(4)]
        public string HomeTeam { get; set; }


        [ColumnName("HomeTeamId"), LoadColumn(5)]
        public float HomeTeamId { get; set; }


        [ColumnName("AwayTeam"), LoadColumn(6)]
        public string AwayTeam { get; set; }


        [ColumnName("AwayTeamId"), LoadColumn(7)]
        public float AwayTeamId { get; set; }


        [ColumnName("Winner"), LoadColumn(8)]
        public string Winner { get; set; }


        [ColumnName("WinnerId"), LoadColumn(9)]
        public float WinnerId { get; set; }


        [ColumnName("HomeTeamGoals"), LoadColumn(10)]
        public float HomeTeamGoals { get; set; }


        [ColumnName("AwayTeamGoals"), LoadColumn(11)]
        public float AwayTeamGoals { get; set; }


    }
}
